---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgapi
  namespace: pgapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgapi
  template:
    metadata:
      labels:
        app: pgapi
    spec:
      containers:
      - name: pgapi
        image: pgapi:latest
        imagePullPolicy: IfNotPresent
        command: ["/app/pgapi","-config-path","/app/config/config.yml"]
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /status
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /status
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 8080
          name: pgapi
        volumeMounts:
        - name: pgapi-config
          mountPath: /app/config
      volumes:
        - name: pgapi-config
          secret:
            secretName: api-secret
---
apiVersion: v1
kind: Service
metadata:
  name: pgapi-svc
  namespace: pgapi
  labels:
    app: pgapi
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: pgapi
  type: NodePort
  selector:
    app: pgapi
